1 ➡️ 2
ignitionrobotics/ign-utils pull request #38
Opened 2022-02-22 20:57 UTC by mjcarroll

# ➡️ Forward port

Port `ign-utils1` to `main`

Branch comparison: https://github.com/ignitionrobotics/ign-utils/compare/main...ign-utils1

**Note to maintainers**: Remember to **Merge** with commit (not squash-merge or rebase)

2022-02-22 22:06 UTC, azeey requested changes

2022-02-22 22:06 UTC, azeey commented on BUILD.bazel
> +PROJECT_MAJOR = 1
Do we want this change?

2022-02-22 22:06 UTC, azeey commented on CMakeLists.txt
> +project(ignition-utils1 VERSION 1.2.0)
I don't think we want this change

2022-02-22 22:06 UTC, azeey commented on CMakeLists.txt
> +ign_configure_project(VERSION_SUFFIX)
I don't think we want this change

2022-02-22 22:06 UTC, azeey commented on Changelog.md
> +## Ignition Utils 1.x
Can you keep the `2.x` section?

2022-02-22 22:18 UTC, mjcarroll commented
Did this one too quickly, also waiting on #37

2022-02-24 17:45 UTC, azeey approved these changes

2022-03-01 01:47 UTC, chapulina approved these changes

2022-03-01 01:48 UTC, merged